name: Orne Leather
favicon: null
layout_spectrum: 0.52122
typography_spectrum: 0.06962947128340602
title: Orne Leather
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#423b33'
    - '#acaba6'
    - '#807973'
    - '#eace9f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
