name: Orne Leather
favicon: null
layout_spectrum: 0.5946671045385301
typography_spectrum: 0.06962947128340602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5177737649064511
  lightness: 0.25414389302022755
  saturation: 0.19886877504177392
  rhythmicContrast: 0.6563241686671972
purpose: []
